import json
from agents import Runner
from agents.extensions.memory.sqlalchemy_session import SQLAlchemySession

from app.db.session import get_db_engine, get_async_session_factory
from app.models.base import Base
from app.models.trading import TradingHistory
from app.schemas.trading import FinalTradingDecision
from app.agents.nodes.manager import create_manager_agent

async def run_trading_desk(
    ticker_input: str,
    interval: str,
    period: str,
    strategy: str,
    user_name: str,
    user_email: str,
    user_phone: str
) -> FinalTradingDecision:
    """
    Executes the multi-agent cognitive trading loop:
    1. Instantiates Trading Desk Manager (and dependent Analyst + Risk Guardrail nodes).
    2. Opens a persistent SQLAlchemySession bound to the Neon PostgreSQL engine.
    3. Runs the multi-agent decision graph.
    4. Enforces strict schema decoding on the JSON response.
    5. Persists the resulting decision record to the trading_history table.
    """
    engine = None
    try:
        engine = get_db_engine()

        # Ensure base metadata exists
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

        # Initialize session tracking for conversational memory
        session = SQLAlchemySession(
            session_id=f"session_{user_email}",
            engine=engine,
            create_tables=True
        )

        manager = create_manager_agent()

        result = await Runner.run(
            manager,
            input=(
                f"Process trade opportunity for asset: '{ticker_input}' using strategy '{strategy}'. "
                f"Please fetch market data using interval='{interval}' and lookback period='{period}'."
            ),
            session=session
        )

        # Strip markdown code fences if generated by the LLM
        text = result.final_output.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines[-1].startswith("```"):
                lines = lines[:-1]
            text = "\n".join(lines).strip()

        data = json.loads(text)
        decision = FinalTradingDecision(**data)

        print("\n" + "=" * 70)
        print("                 FINAL QUANTITATIVE SYSTEM DECISION")
        print("=" * 70)
        print(f"  * ASSET TICKER     : {decision.ticker}")
        print(f"  * SYSTEM ACTION    : {decision.action}")
        print(f"  * RISK COMPLIANCE  : {decision.risk_status}")
        print(f"  * STABLE CAPITAL   : {decision.stable_capital}")
        print(f"  * BUDGET ALLOCATION: {decision.budget_allocation}")
        print(f"  * POSITION ENTRY   : ${decision.ENTRY_PRICE:.2f}" if decision.ENTRY_PRICE > 0 else "  * POSITION ENTRY   : N/A")
        print(f"  * TAKE PROFIT TRGT : ${decision.TAKE_PROFIT:.2f}" if decision.TAKE_PROFIT > 0 else "  * TAKE PROFIT TRGT : N/A")
        print(f"  * STOP LOSS TARGET : ${decision.STOP_LOSS:.2f}" if decision.STOP_LOSS > 0 else "  * STOP LOSS TARGET : N/A")
        print(f"  * JUSTIFICATION    : {decision.justification}")
        print("=" * 70 + "\n")

        # Persist decision outcome to database
        try:
            session_factory = get_async_session_factory(engine)
            async with session_factory() as db_session:
                status_init = "INACTIVE"
                if decision.risk_status == "APPROVED" and decision.action in ("BUY", "STRONG BUY", "SELL", "STRONG SELL"):
                    status_init = "RUNNING"

                new_record = TradingHistory(
                    user_name=user_name,
                    user_email=user_email,
                    user_phone=user_phone,
                    ticker=decision.ticker,
                    action=decision.action,
                    risk_status=decision.risk_status,
                    stable_capital=decision.stable_capital,
                    budget_allocation=decision.budget_allocation,
                    entry_price=str(decision.ENTRY_PRICE),
                    take_profit=str(decision.TAKE_PROFIT),
                    stop_loss=str(decision.STOP_LOSS),
                    justification=decision.justification,
                    status=status_init
                )
                db_session.add(new_record)
                await db_session.commit()
                print("✅ [Database] Trading history record successfully persisted to Neon PostgreSQL.")
        except Exception as db_err:
            print(f"❌ [Database Error] Failed to persist trading record: {db_err}")

        return decision

    except Exception as e:
        print(f"\n[Error] Multi-agent execution crashed or invalid decision payload: {e}")
        if 'result' in locals() and hasattr(result, 'final_output'):
            print("Raw Agent response was:")
            print(result.final_output)
        raise
    finally:
        if engine:
            try:
                await engine.dispose()
                print("🔌 [Database] Asynchronous database connection engine disposed cleanly.")
            except Exception as dispose_err:
                print(f"🔌 [Database Warning] Engine dispose warning: {dispose_err}")
